from python:3.8-slim

COPY ./main/ ./python/
COPY ./requirement.txt ./requirements.txt

RUN pip3 install --upgrade pip \
	&& pip3 install -r requirements.txt \
	&& pip3 install gunicorn \
	&& apt-get update \
	&& apt-get install -y postgresql postgresql-contrib libpq-dev python3-dev netcat \
#	&& chmod +x /entrypoint.sh \
	&& apt-get clean



COPY ./docker/backend/entrypoint.sh ./
RUN chmod +x /entrypoint.sh

CMD ["/bin/bash", "-c", "/entrypoint.sh"]
