version: '3.1'

services:
    db:
        image: postgres:13.1
        container_name: gb_postgres
        privileged: true
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: gb
            POSTGRES_PASSWORD: gbpass
            POSTGRES_DB: todo
    backend:
        container_name: gb_backend
        build:
            context: .
            dockerfile: Dockerfile-backend
        expose:
            - 8080
              #command: bash -c "while true; do echo sleeping...; sleep 2; done"
              #        vloumes:
              #- ./docker/backend/entrypoint.sh:./entrypoint.sh:ro
              #        command: /bin/bash -c /entrypoint.sh
              #        command: bash -c "
              #            ./wait-for-postgres.sh db
              #            && python manage.py migrate
              #            && python manage.py create_data
              #            && gunicorn library.wsgi -b 0.0.0.0:8080
              #            "
        depends_on:
            - db
    nginx:
        container_name: gb_nginx
        image: nginx:stable-alpine
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - backend


