# Generated by Django 3.1.7 on 2021-03-09 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_project_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user_creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='todo.user'),
        ),
    ]
