# Generated by Django 3.1.7 on 2021-04-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_user_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_ops',
            field=models.BooleanField(default=False),
        ),
    ]
